title: Marek Tyluś
logo: /assets/Pic.jpg
#description: 'Fakty są uparte, ale statystyki są bardziej elastyczne' Marek Twain
#description: "hello\n\nworld"
bio: "hello<br>world"
show_downloads: true
google_analytics: 
theme: jekyll-theme-minimal
